---
  - name: Installing passlib (hash.py requirement)
    pip:
      name: passlib
      state: latest
      executable: pip3


  - name: Running the hash.py
    script: /home/pi/raspberry-pi-setup/Files/hash.py
    args:
      executable: python3

  - name: Loading the hashed password
    include_vars: "{{ item }}"
    loop: 
      - ./Files/hashed.yml

  - name: Setting the password
    user:
      name: pi
      state: present
      password: "{{ hash }}"