---
  - name: Installing Python3, pip3
    apt: 
      name: python3 python3-pip
      state: latest

  - name: Installing the hash.py requirements
    pip:
      requirements: ../requirements.txt

  - name: Running the hash.py
    script: /Files/hash.py
    args:
      executable: python3

  - name: Setting the password
    user:
      name: pi
      state: present
      password: "<{ hash }>"