---
  - name: Installing Python3, pip3
    apt: 
      name: python3
      state: latest
    apt:
      name: python3-pip
      state: latest

  - name: Running the hash.py
    script: /Files/hash.py
    args:
      executable: python3

  - name: Setting the password
    user:
      name: pi
      state: present
      password: "{{ hash }}"